### PR TITLE
edit isoFamily plot

### PR DESCRIPTION
**Pull request by anastazie**
1. Add title
2. Add x and y labels
3. Make color same coding as in isoSegmenter
4. Add legend

### CODE REVIEW

**Comment by anastazie** [comment]
Sorry, I am preparing some modifications, but they are not ready for pull request.

**Comment by bunop** [comment]
Thank you, @anastazie; Open a new pull request when you are ready.

**Comment by anastazie** [comment]
Hello,
I finally decided that I will not add anything more to this pull request. Aim of this PR was to make plot generated by isoFamily.py look the same as in article Isochores, Bernardi, 2012.
Here is printscreen:
output

**Comment by bunop** [comment]
Merged. Thank you @anastazie for your interest and contribute to isoSegmenter

**Pull request merged**
